// Background service worker: handles TTS and translation requests
import { TTS_SETTINGS, MESSAGES } from "../shared/constants";
import { extractTextFromImage, getOpenAiTtsAudioBase64, translateText } from "./services/openai.service";

// Create context menu on install
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "read-selected-text",
    title: "Speak selected text",
    contexts: ["selection"],
  });

  chrome.contextMenus.create({
    id: "translate-image",
    title: "Translate & Speak Image",
    contexts: ["image"],
  });
});

// Context menu click: speak text and request translation popup
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "read-selected-text" && info.selectionText) {
    if (!tab?.id) {
      return;
    }

    await sendTranslationPopup(tab.id, info.selectionText);
  } else if (info.menuItemId === "translate-image") {
    if (!tab?.id) {
      return;
    }

    await trySendMessageWithContentScript(tab.id, { type: MESSAGES.UI_SHOW_LOADING });

    try {
      const sourceText = await extractTextFromImage(info.srcUrl);
      await sendTranslationPopup(tab.id, sourceText);
    } catch (error) {
      console.error("Image analysis failed:", error);
      sendTranslationPopup(tab.id, "Could not analyze image. Please try another one.");
    }
  }
});

async function sendTranslationPopup(tabId, text) {
  const delivered = await trySendMessageWithContentScript(tabId, {
    type: MESSAGES.UI_SHOW_TRANSLATION,
    text,
  });

  if (!delivered) return;
}

async function speakWithOpenAiTts(tabId, text) {
  try {
    const audioBase64 = await getOpenAiTtsAudioBase64(text);
    if (!audioBase64) return;

    await ensureOffscreenDocument();
    
    chrome.runtime.sendMessage({
      target: "offscreen",
      type: MESSAGES.AUDIO_PLAY,
      audioBase64,
      tabId,
      format: TTS_SETTINGS.DEFAULT_FORMAT,
    });
  } catch (error) {
    console.error("OpenAI TTS error:", error);
  }
}

async function ensureOffscreenDocument() {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length > 0) {
    return;
  }

  await chrome.offscreen.createDocument({
    url: "src/offscreen/offscreen.html",
    reasons: ["AUDIO_PLAYBACK"],
    justification: "Play text-to-speech audio generated by OpenAI API",
  });
}

async function trySendMessageWithContentScript(tabId, message) {
  const delivered = await trySendMessage(tabId, message);

  if (delivered) return true;

  try {
    await chrome.scripting.executeScript({
      target: { tabId },
      files: ["src/content/content.js"],
    });
  } catch {
    return;
  }

  return trySendMessage(tabId, message);
}

function trySendMessage(tabId, message) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tabId, message, () => {
      if (chrome.runtime.lastError) {
        console.warn("tabs.sendMessage failed:", chrome.runtime.lastError.message);
        resolve(false);
        return;
      }
      resolve(true);
    });
  });
}

// Handle translation request from content script
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === MESSAGES.TRANSLATE) {
    translateText(message.text)
      .then((translation) => sendResponse({ translation }))
      .catch((err) => sendResponse({ error: err.message }));
    return true; // keep channel open for async response
  }

  if (message.type === MESSAGES.TTS_SPEAK) {
    speakWithOpenAiTts(_sender?.tab?.id, message.text);
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.TTS_STOP) {
    stopOffscreenAudio();
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.TTS_PAUSE) {
    sendOffscreenControlMessage("AUDIO_PAUSE");
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.TTS_RESUME) {
    sendOffscreenControlMessage("AUDIO_RESUME");
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.TTS_SEEK) {
    sendOffscreenControlMessage("AUDIO_SEEK", {
      progress: message.progress,
    });
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.AUDIO_PROGRESS) {
    if (Number.isInteger(message.tabId)) {
      forwardToTab(message.tabId, {
        type: MESSAGES.UI_AUDIO_PROGRESS,
        currentTime: message.currentTime,
        duration: message.duration,
        paused: message.paused,
      });
    }
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === MESSAGES.AUDIO_ENDED) {
    if (Number.isInteger(message.tabId)) {
      forwardToTab(message.tabId, {
        type: MESSAGES.UI_AUDIO_ENDED,
        duration: message.duration,
      });
    }
    sendResponse({ ok: true });
    return true;
  }
});

async function stopOffscreenAudio() {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length === 0) {
    return;
  }

  chrome.runtime.sendMessage({
    target: "offscreen",
    type: MESSAGES.AUDIO_STOP,
  });
}

async function sendOffscreenControlMessage(type, extra = {}) {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length === 0) {
    return;
  }

  chrome.runtime.sendMessage({
    target: "offscreen",
    type,
    ...extra,
  });
}

function forwardToTab(tabId, message) {
  chrome.tabs.sendMessage(tabId, message, () => {
    if (chrome.runtime.lastError) {
      console.warn("forwardToTab failed:", chrome.runtime.lastError.message);
    }
  });
}
