// Background service worker: handles TTS and translation requests
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: import.meta.env.VITE_OPENAI_API_KEY,
  dangerouslyAllowBrowser: true,
});

// Create context menu on install
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "readSelectedText",
    title: "Speak selected text",
    contexts: ["selection"],
  });

  chrome.contextMenus.create({
    id: "translate-image",
    title: "Translate & Speak Image",
    contexts: ["image"],
  });
});

// Context menu click: speak text and request translation popup
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "readSelectedText" && info.selectionText) {
    if (!tab?.id) {
      return;
    }

    await sendTranslationPopup(tab.id, info.selectionText);
  } else if (info.menuItemId === "translate-image") {
    if (!tab?.id) {
      return;
    }

    await trySendMessageWithContentScript(tab.id, { type: "SHOW_LOADING" });

    try {
      const sourceText = await extractTextFromImage(info.srcUrl);
      await sendTranslationPopup(tab.id, sourceText);
    } catch (error) {
      console.error("Image analysis failed:", error);
      sendTranslationPopup(tab.id, "Could not analyze image. Please try another one.");
    }
  }
});

async function extractTextFromImage(imageUrl) {
  const response = await client.responses.create({
    model: "gpt-4.1-mini",
    input: [{
      role: "user",
      content: [
        {
          type: "input_text",
          text: "Extract all visible text from this image in English. If there is no text, summarize the main idea in 1–2 sentences in English.",
        },
        {
          type: "input_image",
          image_url: imageUrl,
        },
      ],
    }],
  });
  return response.output_text;
}

async function sendTranslationPopup(tabId, text) {
  const delivered = await trySendMessageWithContentScript(tabId, {
    type: "SHOW_TRANSLATION",
    text,
  });

  if (!delivered) return;
}

async function speakWithOpenAiTts(tabId, text) {
  if (!text || !text.trim()) {
    return;
  }

  try {
    const response = await client.audio.speech.create({
      model: "gpt-4o-mini-tts",
      voice: "marin", //coral
      instructions: "Speak in a cheerful, very sensual, friendly and positive tone.",
      input: text,
      response_format: "mp3",
    });

    const audioBuffer = await response.arrayBuffer();
    const audioBase64 = arrayBufferToBase64(audioBuffer);

    await ensureOffscreenDocument();
    
    chrome.runtime.sendMessage({
      target: "offscreen",
      type: "PLAY_AUDIO",
      audioBase64,
      tabId,
    });
  } catch (error) {
    console.error("OpenAI TTS error:", error);
  }
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";

  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }

  return btoa(binary);
}

async function ensureOffscreenDocument() {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length > 0) {
    return;
  }

  await chrome.offscreen.createDocument({
    url: "src/offscreen.html",
    reasons: ["AUDIO_PLAYBACK"],
    justification: "Play text-to-speech audio generated by OpenAI API",
  });
}

async function trySendMessageWithContentScript(tabId, message) {
  const delivered = await trySendMessage(tabId, message);

  if (delivered) return true;

  try {
    await chrome.scripting.executeScript({
      target: { tabId },
      files: ["src/content.js"],
    });
  } catch {
    return;
  }

  return trySendMessage(tabId, message);
}

function trySendMessage(tabId, message) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tabId, message, () => {
      if (chrome.runtime.lastError) {
        console.warn("tabs.sendMessage failed:", chrome.runtime.lastError.message);
        resolve(false);
        return;
      }
      resolve(true);
    });
  });
}

// Handle translation request from content script
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === "TRANSLATE") {
    translateText(message.text)
      .then((translation) => sendResponse({ translation }))
      .catch((err) => sendResponse({ error: err.message }));
    return true; // keep channel open for async response
  }

  if (message.type === "TTS_SPEAK") {
    speakWithOpenAiTts(_sender?.tab?.id, message.text);
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "TTS_STOP") {
    stopOffscreenAudio();
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "TTS_PAUSE") {
    sendOffscreenControlMessage("PAUSE_AUDIO");
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "TTS_RESUME") {
    sendOffscreenControlMessage("RESUME_AUDIO");
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "TTS_SEEK") {
    sendOffscreenControlMessage("SEEK_AUDIO", {
      progress: message.progress,
    });
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "OFFSCREEN_AUDIO_PROGRESS") {
    if (Number.isInteger(message.tabId)) {
      forwardToTab(message.tabId, {
        type: "OFFSCREEN_AUDIO_PROGRESS",
        currentTime: message.currentTime,
        duration: message.duration,
        paused: message.paused,
      });
    }
    sendResponse({ ok: true });
    return true;
  }

  if (message.type === "OFFSCREEN_AUDIO_ENDED") {
    if (Number.isInteger(message.tabId)) {
      forwardToTab(message.tabId, {
        type: "OFFSCREEN_AUDIO_ENDED",
        duration: message.duration,
      });
    }
    sendResponse({ ok: true });
    return true;
  }
});

async function stopOffscreenAudio() {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length === 0) {
    return;
  }

  chrome.runtime.sendMessage({
    target: "offscreen",
    type: "STOP_AUDIO",
  });
}

async function sendOffscreenControlMessage(type, extra = {}) {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length === 0) {
    return;
  }

  chrome.runtime.sendMessage({
    target: "offscreen",
    type,
    ...extra,
  });
}

function forwardToTab(tabId, message) {
  chrome.tabs.sendMessage(tabId, message, () => {
    if (chrome.runtime.lastError) {
      console.warn("forwardToTab failed:", chrome.runtime.lastError.message);
    }
  });
}

async function translateText(text) {
  const response = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content:
          "You are a translator. Translate the given text to Spanish. Reply with only the translation, no explanations.",
      },
      { role: "user", content: text },
    ],
    max_tokens: 256,
  });
  const r = response.choices[0].message.content.trim();
  console.log("traslation:", r)
  return r
}
