// Background service worker: handles TTS and translation requests
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: import.meta.env.VITE_OPENAI_API_KEY,
  dangerouslyAllowBrowser: true,
});

// Create context menu on install
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "readSelectedText",
    title: "Speak selected text",
    contexts: ["selection"],
  });
});

// Context menu click: speak text and request translation popup
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "readSelectedText" && info.selectionText) {
    if (!tab?.id) {
      return;
    }

    await Promise.allSettled([
      sendTranslationPopup(tab.id, info.selectionText),
      speakWithOpenAiTts(tab.id, info.selectionText),
    ]);
  }
});

async function sendTranslationPopup(tabId, text) {
  const delivered = await trySendMessageWithContentScript(tabId, {
    type: "SHOW_TRANSLATION",
    text,
  });

  if (!delivered) return;
}

async function speakWithOpenAiTts(tabId, text) {
  try {
    const response = await client.audio.speech.create({
      model: "tts-1",
      voice: "shimmer",
      input: text,
      response_format: "mp3",
    });

    const audioBuffer = await response.arrayBuffer();
    const audioBase64 = arrayBufferToBase64(audioBuffer);

    await ensureOffscreenDocument();
    
    chrome.runtime.sendMessage({
      target: "offscreen",
      type: "PLAY_AUDIO",
      audioBase64,
    });
  } catch (error) {
    console.error("OpenAI TTS error:", error);
  }
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";

  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }

  return btoa(binary);
}

async function ensureOffscreenDocument() {
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
  });

  if (existingContexts.length > 0) {
    return;
  }

  await chrome.offscreen.createDocument({
    url: "src/offscreen.html",
    reasons: ["AUDIO_PLAYBACK"],
    justification: "Play text-to-speech audio generated by OpenAI API",
  });
}

async function trySendMessageWithContentScript(tabId, message) {
  const delivered = await trySendMessage(tabId, message);

  if (delivered) return true;

  try {
    await chrome.scripting.executeScript({
      target: { tabId },
      files: ["src/content.js"],
    });
  } catch {
    return;
  }

  return trySendMessage(tabId, message);
}

function trySendMessage(tabId, message) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tabId, message, () => {
      if (chrome.runtime.lastError) {
        console.warn("tabs.sendMessage failed:", chrome.runtime.lastError.message);
        resolve(false);
        return;
      }
      resolve(true);
    });
  });
}

// Handle translation request from content script
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === "TRANSLATE") {
    translateText(message.text)
      .then((translation) => sendResponse({ translation }))
      .catch((err) => sendResponse({ error: err.message }));
    return true; // keep channel open for async response
  }
});

async function translateText(text) {
  const response = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content:
          "You are a translator. Translate the given text to Spanish. Reply with only the translation, no explanations.",
      },
      { role: "user", content: text },
    ],
    max_tokens: 256,
  });
  const r = response.choices[0].message.content.trim();
  console.log("traslation:", r)
  return r
}
